sudo: required

dist: trusty

language: ruby

rvm: 2.4.0

services:
  - docker

before_script:
  - sudo pip install docker-squash

script:
  - docker build -t spec .
  - DOCKER_IMAGE=spec bundle exec rspec -f documentation

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker-squash -t hakatashi/esolang-box spec;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push hakatashi/esolang-box;
    fi

notifications:
  webhooks: http://webhook.hakatashi.com/travis
