sudo: required

dist: trusty

language: ruby

rvm: 2.4.0

services:
  - docker

before_script:
  - wget https://github.com/jwilder/docker-squash/releases/download/v0.2.0/docker-squash-linux-amd64-v0.2.0.tar.gz
  - sudo tar -C /usr/local/bin -xzvf docker-squash-linux-amd64-v0.2.0.tar.gz

script:
  - docker build -t spec .
  - DOCKER_IMAGE=spec bundle exec rspec -f documentation

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker save spec > image.tar;
    sudo /usr/local/bin/docker-squash -i image.tar -o squashed.tar -t hakatashi/esolang-box -verbose;
    sudo tar --delete -f squashed.tar manifest.json;
    docker load < squashed.tar;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push hakatashi/esolang-box;
    fi

notifications:
  webhooks: http://webhook.hakatashi.com/travis
