sudo: required

dist: trusty

language: ruby

rvm: 2.5.0

services:
  - docker

before_install:
  - curl -L https://github.com/dnephin/dobi/releases/download/v0.10/dobi-linux > dobi
  - chmod +x dobi
  - sudo mv dobi /usr/local/bin

script:
  - dobi
  - bundle exec rspec -f documentation --tag v2

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker-squash -t hakatashi/esolang-box spec;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push hakatashi/esolang-box;
    fi

notifications:
  webhooks: http://webhook.hakatashi.com/travis
